apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jenkinsx-eks-3
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "890324431850"
    provider: eks
    region: ap-south-1
    registry: 890324431850.dkr.ecr.ap-south-1.amazonaws.com
  environments:
  - key: dev
    owner: data-platform-skn
    repository: tf2
  - key: staging
  - key: production
  ingress:
    domain: 65.2.47.12.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: nikhil-bora
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-jenkinsx-eks-3-20210517171303518800000005
  - name: reports
    url: s3://reports-jenkinsx-eks-3-20210517171303518500000004
  - name: repository
    url: s3://repository-jenkinsx-eks-3-20210517171303519300000006
  terraform: true
  vault:
    aws:
      dynamoDBRegion: ap-south-1
      dynamoDBTable: vault-unseal-jenkinsx-eks-3-HSVguCcK
      iamUserName: aws-admin-ops
      kmsKeyId: 5c8b3d33-0ccc-47c3-817d-e033b80d7990
      kmsRegion: ap-south-1
      s3Bucket: vault-unseal-jenkinsx-eks-3-20210517171303519300000007
      s3Region: ap-south-1
  webhook: lighthouse
