filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.65.2.47.12.nip.io/
releases:
- chart: dev/tf-spring-demo
  version: 0.0.2
  name: jx-tf-spring-demo
  values:
  - jx-values.yaml
- chart: dev/demo
  version: 0.0.1
  name: jx-demo
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
