# Source: tf-spring-demo/templates/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-tf-spring-demo-tf-spring-demo
  annotations:
    meta.helm.sh/release-name: 'jx-tf-spring-demo'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
